// <auto-generated />
namespace FoodPicker.Migrations.FoodMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RestaurantWebsite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestaurantWebsite));
        
        string IMigrationMetadata.Id
        {
            get { return "201605101823275_RestaurantWebsite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
